Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -173,47 +173,48 @@ jobs:
 #          node: '19.x'
       #- uses: actions/checkout@v3
 
-      - name: Get PR Label
-        #if: ${{ github.ref_name == 'main' }}
-        id: get_labels
-        continue-on-error: true
-        run: |
-          echo "Looking for pull requests associated with commit $GITHUB_SHA..."
-          # Call the GitHub API to list PRs linked to this commit.
-          pr_json=$(curl -s -H "Accept: application/vnd.github.groot-preview+json" \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/commits/$GITHUB_SHA/pulls")
-          # Extract the first PR's number (if available)
-          pr_number=$(echo "$pr_json" | jq -r '.[0].number')
-          if [ "$pr_number" != "null" ] && [ -n "$pr_number" ]; then
-            echo "Found PR number: $pr_number"
-          else
-            echo "No associated PR found for commit $GITHUB_SHA."
-          fi
-          if [ -z "$pr_number" ] || [ "$pr_number" == "null" ]; then
-            echo "Cannot fetch labels because no associated PR number was found."
-            exit 1
-          fi
-          echo "Fetching labels for PR #$pr_number..."
-          # Call the issues API to get labels (PRs are issues too)
-          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels")
-          # Extract labels name
-          labels=$(echo "$response" | jq -r '.[].name' | paste -sd ", " -)
-          if [ -z "$labels" ]; then
-            echo "No labels found on PR #$pr_number."
-          else
-            echo "Labels on PR #$pr_number: $labels"
-            echo "labels=$labels" >> $GITHUB_OUTPUT
-          fi
+      # - name: Get PR Label
+      #   #if: ${{ github.ref_name == 'main' }}
+      #   id: get_labels
+      #   continue-on-error: true
+      #   run: |
+      #     echo "Looking for pull requests associated with commit $GITHUB_SHA..."
+      #     # Call the GitHub API to list PRs linked to this commit.
+      #     pr_json=$(curl -s -H "Accept: application/vnd.github.groot-preview+json" \
+      #       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+      #       "https://api.github.com/repos/${{ github.repository }}/commits/$GITHUB_SHA/pulls")
+      #     # Extract the first PR's number (if available)
+      #     pr_number=$(echo "$pr_json" | jq -r '.[0].number')
+      #     if [ "$pr_number" != "null" ] && [ -n "$pr_number" ]; then
+      #       echo "Found PR number: $pr_number"
+      #     else
+      #       echo "No associated PR found for commit $GITHUB_SHA."
+      #     fi
+      #     if [ -z "$pr_number" ] || [ "$pr_number" == "null" ]; then
+      #       echo "Cannot fetch labels because no associated PR number was found."
+      #       exit 1
+      #     fi
+      #     echo "Fetching labels for PR #$pr_number..."
+      #     # Call the issues API to get labels (PRs are issues too)
+      #     response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+      #       "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels")
+      #     # Extract labels name
+      #     labels=$(echo "$response" | jq -r '.[].name' | paste -sd ", " -)
+      #     if [ -z "$labels" ]; then
+      #       echo "No labels found on PR #$pr_number."
+      #     else
+      #       echo "Labels on PR #$pr_number: $labels"
+      #       echo "labels=$labels" >> $GITHUB_OUTPUT
+      #     fi
       - name: Print label
         id: print_label
         run: |
-            if [ "${{ steps.get_labels.outputs.labels }}" == "orenz-test" ]; then
-              echo "Label is:${{ steps.get_labels.outputs.labels }}"
-              echo "labels=0.1.${{ github.run_number }}" >> $GITHUB_OUTPUT
-            fi
-            echo "Label is:${{ steps.print_label.outputs.labels }}"
+            echo "https://github.com/${{ github.repository }}"
+            # if [ "${{ steps.get_labels.outputs.labels }}" == "orenz-test" ]; then
+            #   echo "Label is:${{ steps.get_labels.outputs.labels }}"
+            #   echo "labels=0.1.${{ github.run_number }}" >> $GITHUB_OUTPUT
+            # fi
+            # echo "Label is:${{ steps.print_label.outputs.labels }}"
 
       # - name: Get Associated PR Number
       #   id: get_pr
